-- AI generated pharma example schema
-- Main Tables: dose_regimens, event, notes_attach

SELECT COUNT(*) FROM pharma_dose_regimens;
SELECT COUNT(*) FROM pharma_event;
SELECT COUNT(*) FROM pharma_notes_attach;


-- dose_regimens Table (Main) - Dosing schedules for trial participants
CREATE TABLE pharma_dose_regimens (
    regimen_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id NUMBER(15) NOT NULL, -- Links to event (many dose_regimens per event)
    patient_id NUMBER(10) NOT NULL,
    medication_id NUMBER(10) NOT NULL,
    trial_id NUMBER(10) NOT NULL,
    frequency VARCHAR2(50) ENCRYPT USING 'AES256', -- e.g., 'twice daily', 'every 8 hours'
    dosage_amount VARCHAR2(50) ENCRYPT USING 'AES256', -- e.g., '100mg'
    start_date DATE NOT NULL,
    end_date DATE,
    long_description CLOB ENCRYPT USING 'AES256',
    instructions VARCHAR2(500) ENCRYPT USING 'AES256',
    status VARCHAR2(20) DEFAULT 'active', -- active, completed, discontinued
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- event Table (Main) - Trial events like visits, data collection points
CREATE TABLE pharma_event (
    event_id NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Large for high volume
    patient_id NUMBER(10) NOT NULL,
    trial_id NUMBER(10) NOT NULL,
    event_type VARCHAR2(50) ENCRYPT USING 'AES256', -- e.g., 'baseline', 'follow-up', 'adverse_event', 'dose_administered'
    event_date TIMESTAMP ENCRYPT USING 'AES256' NOT NULL,
    description VARCHAR2(500) ENCRYPT USING 'AES256',
    status VARCHAR2(20) DEFAULT 'scheduled', -- scheduled, completed, missed
    site_id NUMBER(10),
    investigator_id NUMBER(10),
    long_description CLOB ENCRYPT USING 'AES256',
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- notes_attach Table (Main) - Notes and attachments for dose regimens

CREATE TABLE pharma_notes_attach (
    note_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    regimen_id NUMBER(10) NOT NULL, -- References dose_regimens.regimen_id
    note_text CLOB ENCRYPT USING 'AES256',
    attachment_path VARCHAR2(500) ENCRYPT USING 'AES256',
    attachment_type VARCHAR2(50) ENCRYPT USING 'AES256', -- e.g., 'pdf', 'image', 'document'
    created_by NUMBER(10) ENCRYPT USING 'AES256', -- investigator_id
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Add foreign key constraints for relationships
ALTER TABLE pharma_dose_regimens ADD CONSTRAINT fk_pharma_dose_regimens_event FOREIGN KEY (event_id) REFERENCES pharma_event(event_id);
ALTER TABLE pharma_notes_attach ADD CONSTRAINT fk_pharma_notes_attach_regimen FOREIGN KEY (regimen_id) REFERENCES pharma_dose_regimens(regimen_id);

-- Indexes for performance and relationships
CREATE INDEX idx_pharma_dose_regimens_event ON pharma_dose_regimens(event_id);
CREATE INDEX idx_pharma_notes_attach_regimen ON pharma_notes_attach(regimen_id);



-- cleanup

-- Drop foreign key constraints first to avoid dependency issues
ALTER TABLE pharma_dose_regimens DROP CONSTRAINT fk_pharma_dose_regimens_event;
ALTER TABLE pharma_notes_attach DROP CONSTRAINT fk_pharma_notes_attach_regimen;

-- Drop indexes
DROP INDEX idx_pharma_dose_regimens_event;
DROP INDEX idx_pharma_notes_attach_regimen;

-- Drop tables in reverse order of creation (to handle any remaining dependencies)
DROP TABLE pharma_notes_attach;
DROP TABLE pharma_dose_regimens;
DROP TABLE pharma_event;
